### PR TITLE
[unified_analytics] Ignore errors when reading and writing to session log file

### LINKED ISSUE #2363: unified_analytics code crashes when writing to a file and disk is full
Dart Code extension: 3.130.1
Flutter extension: 3.130.0 (activated)

App: Antigravity
App Host: desktop
Version: mac 1.107.0

Workspace type: Flutter (LSP)
Workspace name: VilagoApp

Dart (3.11.0): /Users/mk/flutter/bin/cache/dart-sdk
Flutter (3.41.1): /Users/mk/flutter (No device)
[12:54:50] [Analyzer] [Info] ==> Content-Length: 6556
[12:54:50] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":52632,"clientInfo":{"name":"Antigravity","version":"1.107.0"},"locale":"en","rootPath":"/Users/mk/Documents/Flutter/VilagoApp","rootUri":"file:///Users/mk/Documents/Flutter/VilagoApp","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"changeAnnotationSupport":{"groupsOnLabel":true}},"configuration":true,"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]},"resolveSupport":{"…
[12:54:50] [Analyzer] [Error] FileSystemException: Cannot open file, path = '/Users/mk/.dart-tool/dart-flutter-telemetry-session.json' (OS Error: No space left on device, errno = 28)
#0      _Link.throwIfError (dart:io/link.dart:358)
dart-lang/sdk#1      _File.openSync (dart:io/file_impl.dart:572)
dart-lang/sdk#2      _File.writeAsBytesSync (dart:io/file_impl.dart:744)
dart-lang/sdk#3      _File.writeAsStringSync (dart:io/file_impl.dart:772)
dart-lang/sdk#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:151)
dart-lang/sdk#5      writeSessionContents (package:unified_analytics/src/utils.dart:304)
dart-lang/sdk#6      UserProperty.getSessionId (package:unified_analytics/src/user_property.dart:68)
dart-lang/sdk#7      UserProperty._toMap (package:unified_analytics/src/user_property.dart:147)
dart-lang/sdk#8      UserProperty.preparePayload (package:unified_analytics/src/user_property…
[12:54:50] [DartToolingDaemon] [Error] FileSystemException: Cannot open file, path = '/Users/mk/.dart-tool/dart-flutter-telemetry-session.json' (OS Error: No space left on device, errno = 28)
[12:54:50] [DartToolingDaemon] [Error] #0      _Link.throwIfError (dart:io/link.dart:358)
dart-lang/sdk#1      _File.openSync (dart:io/file_impl.dart:572)
dart-lang/sdk#2      _File.writeAsBytesSync (dart:io/file_impl.dart:744)
dart-lang/sdk#3      _File.writeAsStringSync (dart:io/file_impl.dart:772)
dart-lang/sdk#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:151)
dart-lang/sdk#5      writeSessionContents (package:unified_analytics/src/utils.dart:304)
dart-lang/sdk#6      UserProperty.getSessionId (package:unified_analytics/src/user_property.dart:68)
dart-lang/sdk#7      UserProperty._toMap (package:unified_analytics/src/user_property.dart:147)
dart-lang/sdk#8      UserProperty.preparePayload (package:unified_analytics/src/user_property.dart:88)
dart-lang/sdk#9      generateRequestBody (package:unified_analytics/src/utils.dart:92)
dart-lang/sdk#10     AnalyticsImpl.send (package:unified_analytics/src/analytics.d…
[12:54:50] [Analyzer] [Warn] LSP Client closed (1 recent restarts recorded)
[12:54:50] [Analyzer] [Warn] Failed to initialize LSP server: Error: Pending response rejected since connection got disposed
[12:54:50] [Analyzer] [Info] Spawning /Users/mk/flutter/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.130.1"]
[12:54:50] [Analyzer] [Info]     PID: 80350
[12:54:50] [Analyzer] [Info] Analysis server exited (1, null)
[12:54:50] [Analyzer] [Warn] Prompting to reload: (The Dart Analyzer has terminated. Please [file an issue on GitHub](https://github.com/dart-lang/sdk/issues/new/choose) with any error from the end of the log.) (actions: Restart Extension, Show Log)

### PR DESCRIPTION
**Pull request by keertip**
fixes #2363 , and #2388

### CODE REVIEW

File: pkgs/unified_analytics/lib/src/log_handler.dart [hunk 1]
```diff
@@ -298,9 +298,14 @@ class LogHandler {
 
         logFile.writeAsStringSync(records.join('\n'));
       }
-    } on FileSystemException {
-      // Logging isn't important enough to warrant raising a
-      // FileSystemException that will surprise consumers of this package.
+    } on Object catch (_) {
```
Comment (bwilkerson) [inline pkgs/unified_analytics/lib/src/log_handler.dart:301]: nit: You don't need the catch clause if you're not going to reference the exception.

**Review by bwilkerson — APPROVED** [review]
