### PR TITLE
Fix symlink loop performance.

### LINKED ISSUE #1728: Cyclic symlinks are followed indefinitely until crashing
Hi thanks for the lib! When I use build_runner it has bugs as follows. It just follows `.symlinks` and `.dart_tool` folder infinitely, then filename is too long.

But IMHO, build_runner **should not** look at symlinks and dart_tool folders! 

```
flutter pub get && flutter packages pub run build_runner watch --delete-conflicting-outputs 
Running "flutter pub get" in proj...                                3.0s
[INFO] Generating build script...
[INFO] Generating build script completed, took 377ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 9.4s

[INFO] There was output on stdout while compiling the build script snapshot, run with `--verbose` to see it (you will need to run a `clean` first to re-snapshot).

[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 12ms

[INFO] Waiting for all file watchers to be ready...
[SEVERE] Error from directory watcher for package:yplusplus

If you see this consistently then it is recommended that you enable the polling file watcher with --use-polling-watcher.


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


FileSystemException: Directory listing failed, path = '/Users/tom/QAPMain/Development/rzzsdxx_frontend/proj/ios/.symlinks/plugins/vision_utils/example/ios/.symlinks/plugins/vision_utils/.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/error_cache/vision_utils/0/example/ios/.symlinks/plugins/vision_utils/.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/error_cache/vision_utils/0/example/ios/.symlinks/plugins/vision_utils/.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/error_cache/vision_utils/0/example/ios/.symlinks/plugins/vision_utils/.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/error_cache/vision_utils/0/example/ios/.symlinks/plugins/vision_utils/.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/error_cache/vision_utils/0/example/ios/.symlinks/plugins/vision_utils/.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/error_cache/vision_utils/1/example/ios/.symlinks/plugins/vision_utils/.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/error_cache/vision_utils/0/example/ios/.symlinks/plugins/vision_utils/example/ios/.symlinks/plugins/sentry_flutter/test/mo' (OS Error: File name too long, errno = 63)
Instance of '_StringStackTrace'

pub finished with exit code 1
```

i.e.

image

### LINKED ISSUE #2170: Fix package:watcher performance when there are multiple symlink cycles
Currently the behavior with symlinks is undefined + untested.

Add test coverage, decide the new behavior, do a breaking release.

As part of this change, fix behavior when there are cyclic symlinks https://github.com/dart-lang/tools/issues/1728

### PR DESCRIPTION
**Pull request by davidmorgan**
Fix #2170
Fix #1728

Use a `Directory.list` replacement that handles symlinks better to avoid severe performance issues with symlink loops on Linux and MacOS.

https://github.com/dart-lang/sdk/issues/61407

Use the `find -L` algorithm, which skips entering a path that's already being traversed. Test using the actual `find -L`.

Add a simple check for the original performance issue that creates a watcher on a directory with a lot of symlink loops and expects it to start up quickly.

### CODE REVIEW

File: pkgs/watcher/lib/src/directory_watcher/directory_list.dart [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+        in directory.directory.list(recursive: false, followLinks: false)) {
+      // Handle links.
+      if (entity is Link) {
+        // Look up their target and target type.
+        final target = entity.targetSync();
+        final targetType = FileSystemEntity.typeSync(target);
+
+        if (targetType == FileSystemEntityType.directory) {
+          // Add links to directories with their target to [subdirectories].
+          subdirectories.add(_ResolvedDirectory(
```
Comment (mraleph) [inline pkgs/watcher/lib/src/directory_watcher/directory_list.dart:87]: Does this not end up ignoring link altogether if it is already visited? e.g. if I do:

```
mkdir tmp/a/b/c
ln -s $PWD/tmp tmp/a/b/c/root
find -L tmp
```

I get:

```
tmp
tmp/a
tmp/a/b
tmp/a/b/c
tmp/a/b/c/root
```

But the current algorithm will just ignore `root` altogether.

Comment (davidmorgan) [reply pkgs/watcher/lib/src/directory_watcher/directory_list.dart:87]: Hmm which `find` are you using? For me that triggers loop detection and does not print `root`.

```
mkdir -p tmp/a/b/c
ln -s $PWD/tmp tmp/a/b/c/root
tmp
tmp/a
tmp/a/b
tmp/a/b/c
find: File system loop detected; ‘tmp/a/b/c/root’ is part of the same file system loop as ‘tmp’.

find --version
find (GNU findutils) 4.10.0
```

Possibly with your `find` the loop link is being reported as a link? You could check with `-type l`. That would be the same way a broken link is reported.

Comment (mraleph) [reply pkgs/watcher/lib/src/directory_watcher/directory_list.dart:87]: I use Mac OS X `find`. FWIW `tree` seems to behave similar, it prints:

```
tmp
└── a
    └── b
        └── c
            └── root -> /Users/vegorov/tmp
```

Anyway it's a minor detail.

Comment (davidmorgan) [reply pkgs/watcher/lib/src/directory_watcher/directory_list.dart:87]: Thanks.

It's easy to change; but if they're reported here as links then the other code in the package will report them like they're files. Doesn't seem particularly useful.

Kept as-is and added to the `listRecursively` doc comment instead

```
/// Skipped links to directories are not mentioned in the directory listing.
```
