### PR TITLE
Fix watching when path has a trailing slash.

### LINKED ISSUE #2293: DirectoryWatcher fails if trailing slash
Copied from https://github.com/dart-lang/tools/issues/2283#issuecomment-3709638209

v1.1.4 works correctly with trailing slashes, but v2.0.0 does not.

In v2.0.0:

DirectoryWatcher('/folder/path') ✅ works
DirectoryWatcher('/folder/path/') ❌ does not

### PR DESCRIPTION
**Pull request by davidmorgan**
Fix #2293.

Trailing slash (or backslash on Windows) is never useful, just remove it, restoring the previous behavior when there is a trailing slash.

Change to undefined behavior: previous versions were a bit relying on normalization done internally to `Directory` methods, but these give surprising results, for example `Directory('/tmp///').listSync()` returns paths with `///` in them. Rather than try to emulate this behavior everywhere to match previous versions, normalize paths to remove them.

### CODE REVIEW

File: pkgs/watcher/test/directory_watcher/file_tests.dart [hunk 1]
```diff
@@ -112,6 +112,25 @@ void _fileTests({required bool isNative}) {
     expect(await queue3HasNext, false);
   });
 
+  // Regression test for https://github.com/dart-lang/tools/issues/2293.
+  test('works with trailing path separator', () async {
```
Comment (jensjoha) [inline pkgs/watcher/test/directory_watcher/file_tests.dart:116]: Maybe tests with more separators? Something like `/////foo//////bar///`

**Review by jensjoha — APPROVED** [review]

File: pkgs/watcher/test/directory_watcher/file_tests.dart (hunk 1 above)
Comment (davidmorgan) [reply pkgs/watcher/test/directory_watcher/file_tests.dart:116]: Done. Thanks!
